"""
HEREDOC PARSER — Extract structured files from LLM heredoc output.

Supports:
- Standard heredoc: cat > /path << 'EOF' ... EOF
- Quoted delimiter: cat > /path << "EOF" ... EOF
- Appending: cat >> /path << 'EOF' ... EOF
- Multi-file blocks with chmod between them
- Recovery from malformed heredocs (nested backticks, missing EOF)
"""

import re
import hashlib
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass
from pathlib import Path


@dataclass
class HeredocFile:
    path: str
    content: str
    mode: str = "create"  # "create" (>), "append" (>>)
    executable: bool = False
    raw_block: str = ""
    hash: str = ""
    
    def __post_init__(self):
        if not self.hash:
            self.hash = hashlib.sha256(self.content.encode()).hexdigest()[:12]


@dataclass
class ParseResult:
    files: List[HeredocFile]
    errors: List[str]
    raw_text: str = ""
    
    @property
    def success(self) -> bool:
        return len(self.files) > 0 and len(self.errors) == 0


# Regex patterns for heredoc extraction
HEREDOC_PATTERN = re.compile(
    r'cat\s+(>\s+|>>\s+)\s*([^\s\n]+)\s+<<\s*[\'"]?([\w_]+)[\'"]?\n(.*?)\n\3',
    re.DOTALL | re.MULTILINE
)

# Alternative: heredoc without quoting the delimiter
HEREDOC_UNQUOTED_PATTERN = re.compile(
    r'cat\s+(>\s+|>>\s+)\s*([^\s\n]+)\s+<<\s*([\w_]+)\n(.*?)\n\3',
    re.DOTALL | re.MULTILINE
)

# chmod pattern
CHMOD_PATTERN = re.compile(r'chmod\s+\+x\s+([^\s\n]+)')

# Simple path validation
PATH_PATTERN = re.compile(r'^[\w/\-\._~]+$')


def extract_heredocs(text: str) -> ParseResult:
    """
    Extract all heredoc file blocks from LLM output.
    Returns structured files with metadata.
    """
    files: List[HeredocFile] = []
    errors: List[str] = []
    seen_paths = set()
    
    # Find all heredoc blocks
    matches = list(HEREDOC_PATTERN.finditer(text))
    if not matches:
        matches = list(HEREDOC_UNQUOTED_PATTERN.finditer(text))
    
    for i, match in enumerate(matches):
        redirect = match.group(1).strip()
        file_path = match.group(2).strip()
        delimiter = match.group(3)
        content = match.group(4)
        
        # Validate path
        if not file_path or file_path.startswith(('http', 'https')):
            errors.append(f"Block {i+1}: Invalid or missing file path")
            continue
        
        # Detect append vs create
        mode = "append" if ">>" in redirect else "create"
        
        # Clean content: remove trailing whitespace but preserve structure
        content = content.rstrip()
        
        # Check for duplicate paths
        if file_path in seen_paths:
            errors.append(f"Block {i+1}: Duplicate path '{file_path}' — overwriting previous")
        seen_paths.add(file_path)
        
        files.append(HeredocFile(
            path=file_path,
            content=content,
            mode=mode,
            raw_block=match.group(0)
        ))
    
    # Detect chmod +x commands and mark files executable
    chmod_matches = CHMOD_PATTERN.findall(text)
    for chmod_path in chmod_matches:
        for f in files:
            if f.path == chmod_path or f.path.endswith(chmod_path.split('/')[-1]):
                f.executable = True
    
    # Check for files mentioned in tree but not generated
    tree_mentions = re.findall(r'[\s\-•*]\s*([\w/\-\._]+\.[\w]+)\s*$', text, re.MULTILINE)
    for mention in tree_mentions:
        if mention not in seen_paths and not any(f.path.endswith(mention) for f in files):
            # Not an error, just informational
            pass
    
    if not files and not errors:
        errors.append("No heredoc blocks found in output")
    
    return ParseResult(files=files, errors=errors, raw_text=text)


def generate_deploy_script(files: List[HeredocFile], project_name: str = "project") -> str:
    """
    Generate a deploy.sh script from extracted heredoc files.
    Orders files by dependency: dirs first, then configs, then code.
    """
    if not files:
        return "#!/bin/bash\n# No files to deploy\n"
    
    # Sort files: create directories first, then by path depth
    sorted_files = sorted(files, key=lambda f: (
        0 if f.path.endswith(('.md', '.txt', 'README')) else 1,
        0 if 'requirements' in f.path else 1,
        f.path.count('/')
    ))
    
    lines = [
        "#!/bin/bash",
        f"# Deploy script for: {project_name}",
        f"# Generated by Peacock Engine Project Generator",
        f"# Files: {len(files)}",
        "",
        "set -e  # Exit on error",
        "",
    ]
    
    # Create parent directories
    dirs = set()
    for f in sorted_files:
        parent = str(Path(f.path).parent)
        if parent not in ('.', '/', ''):
            dirs.add(parent)
    
    if dirs:
        lines.append("# Create directory structure")
        for d in sorted(dirs):
            lines.append(f'mkdir -p "{d}"')
        lines.append("")
    
    # Write files
    lines.append("# Deploy files")
    for f in sorted_files:
        lines.append(f"")
        lines.append(f"# --- {f.path} ---")
        if f.mode == "append":
            lines.append(f"cat >> '{f.path}' << 'PEACOCK_EOF'")
        else:
            lines.append(f"cat > '{f.path}' << 'PEACOCK_EOF'")
        lines.append(f.content)
        lines.append("PEACOCK_EOF")
        if f.executable:
            lines.append(f"chmod +x '{f.path}'")
    
    lines.extend([
        "",
        "echo \"✅ Deployment complete for {project_name}\"",
    ])
    
    return "\n".join(lines)


def generate_file_tree(files: List[HeredocFile]) -> str:
    """Generate a visual file tree from extracted files."""
    if not files:
        return "(empty)"
    
    paths = sorted(f.path for f in files)
    lines = []
    
    for path in paths:
        parts = path.split('/')
        depth = len(parts) - 1
        indent = "  " * depth
        name = parts[-1]
        lines.append(f"{indent}├── {name}")
    
    return "\n".join(lines)


def validate_heredoc_syntax(text: str) -> Tuple[bool, List[str]]:
    """
    Validate that heredoc blocks are well-formed.
    Returns (is_valid, list_of_issues).
    """
    issues = []
    
    # Check for nested triple backticks inside heredocs (common LLM mistake)
    heredoc_blocks = re.findall(r'cat\s+>\s+[^\n]+<<\s*[\'"]?\w+[\'"]?\n(.*?)\n\w+', text, re.DOTALL)
    for i, block in enumerate(heredoc_blocks):
        if '```' in block:
            issues.append(f"Block {i+1}: Contains nested triple backticks — will corrupt file content")
        if 'EOF' in block and not block.strip().endswith('EOF'):
            # Might be an early EOF termination
            pass
    
    # Check for unclosed heredocs
    open_heredocs = len(re.findall(r'cat\s+>\s+[^\n]+<<\s*[\'"]?\w+[\'"]?\n', text))
    close_heredocs = len(re.findall(r'\nEOF\n|\nEND\n', text))
    if open_heredocs != close_heredocs:
        issues.append(f"Heredoc imbalance: {open_heredocs} opens, {close_heredocs} closes detected")
    
    return len(issues) == 0, issues


def sanitize_path(path: str) -> Optional[str]:
    """
    Sanitize a file path from LLM output.
    Removes dangerous patterns, validates structure.
    Returns None if path is invalid.
    """
    if not path or not isinstance(path, str):
        return None
    
    path = path.strip()
    
    # Reject dangerous patterns
    dangerous = ['..', '~', '$', '`', '|', ';', '&', '<', '>', '*', '?']
    for d in dangerous:
        if d in path:
            return None
    
    # Must look like a reasonable path
    if not PATH_PATTERN.match(path):
        return None
    
    # Must have a filename
    if '/' not in path and '.' not in path:
        return None
    
    return path
