"""
PEACOCK ENGINE — Plan Storage & Management (TB-014 / TB-025)
Persistent storage and lifecycle tracking for ExecutionPlans generated by TB-011.

Scope:
  • Save/load ExecutionPlan instances with full chunk text and routing decisions
  • Track plan-level status: pending | running | completed | failed | archived
  • Track per-chunk status and any manual routing overrides
  • List, filter, update, and delete plans (SQLite-indexed, no JSON scan)
  • Store plans as JSON files under the project-relative `plans/` directory

References:
  • app.core.plan_generator (TB-011)
  • app.core.proxy_rules (TB-012) — manual overrides originate here
  • app.core.index_store (TB-025) — fast listing via SQLite
"""

import json
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Literal, Optional, Any

from app.core.plan_generator import ExecutionPlan, ChunkPlan
from app.core.index_store import index_store


# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

PLANS_DIR = Path(__file__).resolve().parent.parent.parent / "plans"
PLAN_STATUSES = {"pending", "queued", "running", "completed", "failed", "archived"}
CHUNK_STATUSES = {"pending", "running", "completed", "failed"}


# ═══════════════════════════════════════════════════════════════════════════════
# MANAGER
# ═══════════════════════════════════════════════════════════════════════════════

class PlanManager:
    """
    File-backed storage manager for ExecutionPlans.

    Each plan is stored as `{PLANS_DIR}/{plan_id}.json` using the full
    serialization from ExecutionPlan.to_full_dict() so chunk text and status
    history survive round-trips.

    Usage:
        plan = await generate_plan("/path/to/file.py")
        plan_id = PlanManager.save(plan)

        loaded = PlanManager.load(plan_id)
        PlanManager.update_chunk_status(plan_id, chunk_id=0, status="running")
        PlanManager.set_chunk_override(plan_id, chunk_id=1, route="proxy")

        for meta in PlanManager.list_plans(status="pending", limit=50, offset=0):
            print(meta["plan_id"], meta["file_path"])
    """

    # ─────────────────────────── INTERNAL HELPERS ───────────────────────────

    @staticmethod
    def _ensure_dir() -> None:
        PLANS_DIR.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _plan_path(plan_id: str) -> Path:
        return PLANS_DIR / f"{plan_id}.json"

    @staticmethod
    def _generate_id() -> str:
        """Generate a short URL-safe plan ID."""
        return f"plan_{uuid.uuid4().hex[:16]}"

    @staticmethod
    def _now() -> float:
        return time.time()

    @classmethod
    def _validate_plan_status(cls, status: str) -> None:
        if status not in PLAN_STATUSES:
            raise ValueError(f"Invalid plan status '{status}'. Must be one of: {PLAN_STATUSES}")

    @classmethod
    def _validate_chunk_status(cls, status: str) -> None:
        if status not in CHUNK_STATUSES:
            raise ValueError(f"Invalid chunk status '{status}'. Must be one of: {CHUNK_STATUSES}")

    # ─────────────────────────── PUBLIC API ───────────────────────────

    @classmethod
    def save(cls, plan: ExecutionPlan, plan_id: Optional[str] = None) -> str:
        """
        Persist a plan. Returns the assigned or provided plan ID.

        Args:
            plan: The ExecutionPlan to store
            plan_id: Optional stable ID; if omitted, a UUID is generated
        """
        cls._ensure_dir()
        pid = plan_id or cls._generate_id()
        path = cls._plan_path(pid)
        path.write_text(plan.to_full_json(indent=2), encoding="utf-8")
        index_store.index_plan(pid, plan.to_full_dict())
        return pid

    @classmethod
    def load(cls, plan_id: str) -> ExecutionPlan:
        """Rehydrate a plan from storage."""
        path = cls._plan_path(plan_id)
        if not path.exists():
            raise FileNotFoundError(f"Plan not found: {plan_id}")
        data = json.loads(path.read_text(encoding="utf-8"))
        return ExecutionPlan.from_dict(data)

    @classmethod
    def exists(cls, plan_id: str) -> bool:
        """Check whether a plan exists on disk."""
        return cls._plan_path(plan_id).exists()

    @classmethod
    def list_plans(
        cls,
        status: Optional[Literal["pending", "running", "completed", "failed", "archived"]] = None,
        model_id: Optional[str] = None,
        limit: int = 100,
        offset: int = 0,
    ) -> List[Dict[str, Any]]:
        """
        Return metadata for stored plans, newest first.
        Uses SQLite index exclusively (TB-025). No JSON fallback.
        """
        return index_store.list_plans(
            status=status, model_id=model_id, limit=limit, offset=offset
        )

    @classmethod
    def count_plans(
        cls,
        status: Optional[str] = None,
        model_id: Optional[str] = None,
    ) -> int:
        """Return the total count of plans matching filters."""
        return index_store.count_plans(status=status, model_id=model_id)

    @classmethod
    def update_plan_status(
        cls,
        plan_id: str,
        status: Literal["pending", "running", "completed", "failed", "archived"],
    ) -> ExecutionPlan:
        """
        Update the top-level status of a plan.

        Automatically sets completed_at when transitioning to a terminal state.
        """
        cls._validate_plan_status(status)
        plan = cls.load(plan_id)
        plan.status = status
        if status in {"completed", "failed", "archived"}:
            plan.completed_at = cls._now()
        cls.save(plan, plan_id=plan_id)
        index_store.index_plan(plan_id, plan.to_full_dict())
        return plan

    @classmethod
    def update_chunk_status(
        cls,
        plan_id: str,
        chunk_id: int,
        status: Literal["pending", "running", "completed", "failed"],
        error: Optional[str] = None,
    ) -> ExecutionPlan:
        """Update status for a single chunk."""
        cls._validate_chunk_status(status)
        plan = cls.load(plan_id)

        chunk = next((c for c in plan.chunks if c.chunk_id == chunk_id), None)
        if chunk is None:
            raise ValueError(f"Chunk {chunk_id} not found in plan {plan_id}")

        chunk.status = status
        if error is not None:
            chunk.error = error
        if status == "completed":
            chunk.completed_at = cls._now()

        # Auto-roll plan status based on aggregate chunk state
        statuses = {c.status for c in plan.chunks}
        if statuses == {"completed"}:
            plan.status = "completed"
            plan.completed_at = cls._now()
        elif "failed" in statuses and plan.status not in {"completed", "failed"}:
            plan.status = "running" if statuses != {"failed"} else "failed"
            if plan.status == "failed":
                plan.completed_at = cls._now()

        cls.save(plan, plan_id=plan_id)
        return plan

    @classmethod
    def delete(cls, plan_id: str) -> bool:
        """Remove a plan from storage. Returns True if it existed."""
        path = cls._plan_path(plan_id)
        if path.exists():
            path.unlink()
            index_store.delete_plan(plan_id)
            return True
        return False

    @classmethod
    def set_chunk_override(
        cls,
        plan_id: str,
        chunk_id: int,
        route: Literal["direct", "proxy"],
    ) -> ExecutionPlan:
        """Apply a manual routing override to a chunk."""
        if route not in {"direct", "proxy"}:
            raise ValueError("route must be 'direct' or 'proxy'")
        plan = cls.load(plan_id)
        chunk = next((c for c in plan.chunks if c.chunk_id == chunk_id), None)
        if chunk is None:
            raise ValueError(f"Chunk {chunk_id} not found in plan {plan_id}")
        chunk.manual_override = route
        cls.save(plan, plan_id=plan_id)
        return plan

    @classmethod
    def clear_chunk_override(cls, plan_id: str, chunk_id: int) -> ExecutionPlan:
        """Remove a manual routing override from a chunk."""
        plan = cls.load(plan_id)
        chunk = next((c for c in plan.chunks if c.chunk_id == chunk_id), None)
        if chunk is None:
            raise ValueError(f"Chunk {chunk_id} not found in plan {plan_id}")
        chunk.manual_override = None
        cls.save(plan, plan_id=plan_id)
        return plan

    @classmethod
    def get_recent_executions(cls, limit: int = 20) -> List[Dict[str, Any]]:
        """Return the most recent execution log entries across all plans.

        Uses SQLite history_runs index exclusively (TB-030). No JSON scan.
        """
        from app.core.index_store import index_store
        return index_store.list_history_runs(limit=limit, offset=0)

    @classmethod
    def get_chunk_summary(cls, plan_id: str) -> Dict[str, Any]:
        """Return a concise per-chunk summary for UI / monitoring."""
        plan = cls.load(plan_id)
        return {
            "plan_id": plan_id,
            "plan_status": plan.status,
            "total_chunks": len(plan.chunks),
            "chunks": [
                {
                    "chunk_id": c.chunk_id,
                    "route": c.manual_override or c.route,
                    "original_route": c.route,
                    "manual_override": c.manual_override,
                    "status": c.status,
                    "token_count": c.token_count,
                    "key_label": c.key_label,
                    "estimated_seconds": c.estimated_seconds,
                    "wait_seconds": c.wait_seconds,
                    "completed_at": c.completed_at,
                    "error": c.error,
                }
                for c in plan.chunks
            ],
        }


# ═══════════════════════════════════════════════════════════════════════════════
# CONVENIENCE
# ═══════════════════════════════════════════════════════════════════════════════

def save_plan(plan: ExecutionPlan, plan_id: Optional[str] = None) -> str:
    return PlanManager.save(plan, plan_id=plan_id)


def load_plan(plan_id: str) -> ExecutionPlan:
    return PlanManager.load(plan_id)
